routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Authentication Routes
Auth::routes();

// Page Routes
Route::get('/', ['as' => '/', 'uses' => 'PagesController@getIndex']);
Route::get('about', ['as' => 'about', 'uses' => 'PagesController@getAbout']);
Route::get('frequently-asked-questions', ['as' => 'help', 'uses' => 'PagesController@getHelp']);
Route::get('search', ['as' => 'search.index', 'uses' => 'PagesController@getSearch']);
Route::get('list-your-business', ['as' => 'list-your-business', 'uses' => 'PagesController@getListYourBusiness']);
Route::get('terms-and-conditions', ['as' => 'terms', 'uses' => 'PagesController@getTerms']);
Route::get('privacy-policy', ['as' => 'privacy', 'uses' => 'PagesController@getPrivacy']);
Route::get('cookie-policy', ['as' => 'cookie', 'uses' => 'PagesController@getCookie']);

// Admin Routes

// Admin Main Nan Routes
Route::get('admin', ['as' => 'admin', 'uses' => 'AdminController@getIndex']);
Route::get('admin/services', ['as' => 'admin.services', 'uses' => 'ServiceController@index']);
Route::get('admin/treatments', ['as' => 'admin.treatments', 'uses' => 'TreatmentController@index']);
Route::get('admin/tags', ['as' => 'admin.tags', 'uses' => 'TagController@index']);
Route::get('admin/appointments', ['as' => 'admin.appointments', 'uses' => 'AppointmentController@index']);
Route::get('admin/settings', ['as' => 'admin.settings', 'uses' => 'SettingController@index']);

// Admin User Routes
Route::get('admin/users', ['as' => 'admin.users', 'uses' => 'UserController@index']);
Route::get('admin/users/edit/{id}', ['as' => 'admin.users.edit', 'uses' => 'UserController@edit']);
Route::get('admin/user/create', ['as' => 'admin.users.create', 'uses' => 'UserController@create']);
Route::post('admin/user/create', ['as' => 'user.store', 'uses' => 'UserController@store']);
Route::put('user/{id}', ['as' => 'user.update', 'uses' => 'UserController@update']);

// Admin Supplier Routes
Route::get('admin/suppliers', ['as' => 'admin.suppliers', 'uses' => 'AdminController@getSuppliers']);
Route::get('admin/suppliers/edit/{id}', ['as' => 'admin.suppliers.edit', 'uses' => 'AdminController@getSupplierEdit']);
Route::get('admin/suppliers/show/{id}', ['as' => 'admin.suppliers.show', 'uses' => 'AdminController@getSupplierShow']);

// Admin Customer Routes
Route::get('admin/customers', ['as' => 'admin.customers', 'uses' => 'AdminController@getCustomers']);
Route::get('admin/customers/edit/{id}', ['as' => 'admin.customers.edit', 'uses' => 'AdminController@getCustomerEdit']);
Route::get('admin/customers/show/{id}', ['as' => 'admin.customers.show', 'uses' => 'AdminController@getCustomerShow']);

// Admin Appointments Routes
Route::get('admin/appointment/edit/{id}', ['as' => 'admin.appointment.edit', 'uses' => 'AppointmentController@edit']);

// Customer Routes
Route::get('customer', ['as' => 'customer.index', 'uses' => 'CustomerController@index']);
Route::get('customer/bookings', ['as' => 'customer.bookings', 'uses' => 'CustomerController@getBookings']);
Route::put('customer/{id}', ['uses' => 'CustomerController@update', 'as' => 'customer.update']);

// Booking Routes & Paypal Routes
Route::resource('booking', 'AppointmentController', ['except' => ['destroy', 'create', 'index', 'store']]);

Route::get('booking', ['as' => 'booking.create', 'uses' => 'AppointmentController@create']);
//Route::post('booking/create', ['as' => 'booking.create', 'uses' => 'AppointmentController@create']);

Route::get('booking-status', ['as' => 'booking.status','uses' => 'PayPalController@getPayWithPaypal']);

Route::post('booking', ['as' => 'addmoney.paypal','uses' => 'PayPalController@postPayWithPaypal']);
Route::get('paypal', ['as' => 'payment.status','uses' => 'PayPalController@getPaymentStatus']);

// Tag Routes
Route::resource('tag', 'TagController', ['except' => ['show', 'create', 'index']]);

// Treatment Routes
Route::resource('treatment', 'TreatmentController', ['except' => ['create', 'show', 'index']]);

// Service Routes
Route::resource('service', 'ServiceController', ['except' => ['create', 'index']]);

// Supplier Routes
Route::get('supplier', ['as' => 'supplier', 'uses' => 'SupplierController@index']);
Route::get('supplier/register', ['as' => 'supplier.register', 'uses' => 'PagesController@getSupplierRegistration']);
Route::get('supplier/availability', ['as' => 'supplier.availability', 'uses' => 'SupplierController@getAvailability']);
Route::get('supplier/holidays', ['as' => 'supplier.holiday', 'uses' => 'SupplierController@getHoliday']);

Route::get('supplier/services', ['as' => 'supplier.services', 'uses' => 'SupplierController@getServices']);
Route::get('supplier/create', ['as' => 'supplier.create', 'uses' => 'SupplierController@getCreateListing']);
Route::get('supplier/edit/{id}', ['as' => 'supplier.edit', 'uses' => 'SupplierController@getServiceEdit']);

Route::post('supplier/register', ['as' => 'supplier.register', 'uses' => 'Auth\RegisterController@register']);
Route::post('supplier/{user_id}', ['uses' => 'SupplierController@store', 'as' => 'supplier.store']);
Route::put('supplier/{id}', ['uses' => 'SupplierController@update', 'as' => 'supplier.update']);

Route::get('supplier/appointments', ['as' => 'supplier.appointments', 'uses' => 'SupplierController@getAppointments']);

Route::get('supplier/appointment/{id}', ['as' => 'supplier.appointment.show', 'uses' => 'SupplierController@getShowAppointment']);
Route::get('supplier/appointment/edit/{id}', ['as' => 'supplier.appointment.edit', 'uses' => 'SupplierController@getEditAppointment']);

// Holiday Routes
Route::resource('holiday', 'HolidayController', ['except' => ['index', 'update', 'edit', 'create', 'show']]);

// Setting Routes
Route::resource('setting', 'SettingController', ['except' => ['create', 'show', 'index', 'edit', 'store', 'destroy']]);

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
	protected $hidden = ['created_at', 'updated_at'];

	//	Tags belong to many services
    public function services() {
		return $this->belongsToMany('App\Service');
	}

//		Tags belong to many posts
//		public function posts() {
//				return $this->belongsToMany('App\Post');
//		}
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use App\Tag;
use Illuminate\Http\Request;
use Session;

class TagController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:super-admin|customer-service-rep|supplier');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
		$tagSlug = '{{ tagSlug | slugify }}';

		$data = [];
		$data['slug'] = $tagSlug;

		return view('tags.index')->with(compact('data'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
		if ($request->ajax()) {
			try {
				// Validate the Data
				$this->validate($request, array(
					'name'       => 'required|max:255',
					'slug'       => 'required|alpha_dash|min:1|max:255|unique:tags,slug',
				));

				// Store the Data in the Database
				$tag = new Tag;

				$tag->name = $request->name;
				$tag->slug = $request->slug;

				$tag->save();

				return response()->json($tag);

			}
			catch(\Exception $e) {

				return response()->json($e->getMessage(), 422);
			}
		}

		$this->validate($request, array(
			'name'       => 'required|max:255',
			'slug'        => 'required|alpha_dash|min:1|max:255|unique:tags,slug',
		));

		// Create Tag in DB
		$tag = new Tag;
		$tag->name = $request->name;
		$tag->slug = $request->slug;

		$tag->save();

		// Create Flash Session Message
		Session::flash('success', 'Treatment Type Created');

		// Redirect to Page
		return redirect()->back();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
		$tag = Tag::find($id);

		return view('tags.edit')->with(compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
		$tag = Tag::find($id);

		$this->validate($request, array(
			'name'       => 'required|max:255',
			'slug'        => "required|alpha_dash|min:1|max:255|unique:tags,slug,$id",
		));

		$tag->name = $request->name;
		$tag->slug = $request->slug;

		$tag->save();

		// Create Flash Session Message
		Session::flash('success', 'Tag Updated');

		return redirect()->route('admin.tags');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

		$tag = Tag::find($id);

		$tag->services()->detach();
//		$tag->posts()->detach();

		$tag->delete();

		Session::flash('success', 'The Tag was successfully deleted.');

		return redirect()->route('admin.tags');
    }
}

resources/views/tags/edit.blade.php
{{--Dashboard Page--}}

@extends('layouts.admin')

@section('title', 'Edit Tag')

@section('stylesheets')
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    {!! Html::style('bower_components/parsleyjs/src/parsley.css') !!}
@stop

@section('content')

    <div id="admin_header">
        @include('partials.admin._toggle')

        <h2>
            <i class="fa fa-tags mr-10"></i> Tags
        </h2>

        <span class="pull-right">
            <a href="{{ route('/') }}" class="btn btn-md btn-blank"><i class="fa fa-home"></i> Visit Site</a>
        </span>
    </div>

    <div id="action_panel" class="bg-beige">
        <h5>There {{ $tags->count() === 1 ? 'is' : 'are' }} <span class="badge">{{ $tags->count() }}</span> tag{{ $tags->count() === 1 ? '' : 's' }} added.</h5>
        <div class="clearfix"></div>
    </div>

    <section>
        <div class="container-fluid">
            @if($tags->count() === 0)
                <div class="row">
                    <div class="col-sm-12">
                        <p>You have not added any treatments.</p>
                    </div>
                </div>

            @else
                <div class="row">

                    <div class="col-sm-8">
                        {{ Form::model($tag, ['route'=> ['tag.update', $tag->id], 'data-parsley-validate' => '', 'method' => 'PUT']) }}
                            <div class="well bg-light-gray">
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-sm-4">
                                            {{ Form::label('name', 'Tag Name', ['class' => ' text-left control-label']) }}
                                        </div>
                                        <div class="col-sm-8">
                                            {{ Form::text('name', null, ['class' => 'form-control', 'required' => '']) }}
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-sm-4">
                                            {{ Form::label('slug','Slug') }}
                                        </div>

                                        <div class="col-sm-8">
                                            {{ Form::text('slug', null, ['class' => 'form-control']) }}
                                        </div>
                                    </div>
                                </div>
                            </div>

                            {{ Form::submit('update treatment', ['class' => 'btn btn-blue btn-md']) }}

                        {{ Form::close() }}
                    </div>

                </div>
            @endif

        </div>
    </section>


@stop

@section('scripts')
    {!! Html::script('bower_components/parsleyjs/dist/parsley.min.js') !!}
@endsection

resources/views/tags/index.blade.php
@extends('layouts.admin')

@section('title', 'Tags')

@section('stylesheets')
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    {!! Html::style('bower_components/parsleyjs/src/parsley.css') !!}
@stop

@section('content')

    <div id="admin_header">
        @include('partials.admin._toggle')

        <h2>
            <i class="fa fa-tags mr-10"></i> Tags
        </h2>

        <span class="pull-right">
            <a href="{{ route('/') }}" class="btn btn-md btn-blank"><i class="fa fa-home"></i> Visit Site</a>
        </span>
    </div>

    <div id="action_panel" class="bg-beige">
        <h5>There {{ $tags->count() === 1 ? 'is' : 'are' }} <span class="badge">{{ $tags->count() }}</span> tag{{ $tags->count() === 1 ? '' : 's' }} added.</h5>

        <div class="clearfix"></div>
    </div>

    <section>
        <div class="container-fluid">
            <div class="row">

                <div class="col-sm-6">
                    @if($tags->count() === 0)

                        <p>You do not have any tags created.</p>

                    @else

                        <div class="panel panel-body panel-default npadding">
                            <div class="table-responsive">
                                <table id="tags-index" class="table table-bordered">
                                    <thead class="bg-blue nb-radius">
                                    <th>Name</th>
                                    <th>Slug</th>
                                    <th class="nbright" style="width:120px"></th>
                                    </thead>

                                    <tbody>
                                    @foreach($tags as $tag)

                                        <tr id="service-{{ $tag->id }}">
                                            <td>
                                                <span class="">{{ $tag->name }}</span>
                                            </td>
                                            <td>
                                                <span class="">{{ $tag->slug }}</span>
                                            </td>
                                            <td class="text-right">
                                                <a href="{{ route('tag.edit', $tag->id) }}" class="text-dark-gray small">edit</a>
                                                @if(Entrust::hasRole('super-admin'))
                                                    |
                                                    <a role="button" data-toggle="collapse" href="#verifyDelete-{{ $tag->id }}" aria-expanded="false" aria-controls="verifyDelete-{{ $tag->id }}" data-parent="#tags-index" class="text-danger small">[delete]</a>
                                                @endif
                                            </td>
                                        </tr>

                                        <tr class="bg-danger npadding">
                                            <td class="npadding bt-dark-gray" colspan="3">
                                                <div id="verifyDelete-{{ $tag->id }}" class="collapse">
                                                    <div class="pl-10 pt-10 pb-10 pr-10 text-center">
                                                        <p class="medium">Are you sure you want to delete this tag? This is permanent.</p>
                                                        {!! Form::open(['route' => ['tag.destroy', $tag->id], 'method' => 'DELETE']) !!}
                                                        {{ Form::button('<i class="fa fa-trash"></i> delete', ['class' => 'btn btn btn-danger btn-sm', 'role' => 'button', 'type' => 'submit']) }}

                                                        {!! Form::close() !!}
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>

                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>

                    @endif



                </div>

                <div class="col-lg-5 col-lg-offset-1 col-sm-6">
                    @if(Entrust::hasRole('super-admin') || Entrust::hasRole('customer-service-rep'))
                        {{ Form::open(['route'=> ['tag.store'], 'data-parsley-validate' => '']) }}

                        <div class="well bg-light-gray">
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-sm-4">
                                        {{ Form::label('name', 'Tag Name', ['class' => ' text-left control-label']) }}
                                    </div>
                                    <div class="col-sm-8">
                                        {{ Form::text('name', null, ['class' => 'form-control', 'required' => '', 'ng-model' => 'tagSlug']) }}
                                    </div>
                                    {{ Form::text('slug', $data['slug'], ['class' => 'hidden']) }}
                                </div>
                            </div>
                        </div>

                        {{ Form::submit('create new', ['class' => 'btn btn-blue btn-md']) }}
                        {{ Form::close() }}
                    @else
                        <p>
                            You need to be an admin to create a new treatment type.
                        </p>
                    @endif


                </div>
            </div>

        </div>
    </section>


@endsection

@section('scripts')
    {!! Html::script('bower_components/parsleyjs/dist/parsley.min.js') !!}
    {!! Html::script('bower_components/angular/angular.min.js') !!}
    {!! Html::script('bower_components/angular-slugify/angular-slugify.js') !!}
    {!! Html::script('dist/js/supplierCreate.js') !!}
@endsection