routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Authentication Routes
Auth::routes();

// Page Routes
Route::get('/', ['as' => '/', 'uses' => 'PagesController@getIndex']);
Route::get('about', ['as' => 'about', 'uses' => 'PagesController@getAbout']);
Route::get('frequently-asked-questions', ['as' => 'help', 'uses' => 'PagesController@getHelp']);
Route::get('search', ['as' => 'search.index', 'uses' => 'PagesController@getSearch']);
Route::get('list-your-business', ['as' => 'list-your-business', 'uses' => 'PagesController@getListYourBusiness']);
Route::get('terms-and-conditions', ['as' => 'terms', 'uses' => 'PagesController@getTerms']);
Route::get('privacy-policy', ['as' => 'privacy', 'uses' => 'PagesController@getPrivacy']);
Route::get('cookie-policy', ['as' => 'cookie', 'uses' => 'PagesController@getCookie']);

// Admin Routes

// Admin Main Nan Routes
Route::get('admin', ['as' => 'admin', 'uses' => 'AdminController@getIndex']);
Route::get('admin/services', ['as' => 'admin.services', 'uses' => 'ServiceController@index']);
Route::get('admin/treatments', ['as' => 'admin.treatments', 'uses' => 'TreatmentController@index']);
Route::get('admin/tags', ['as' => 'admin.tags', 'uses' => 'TagController@index']);
Route::get('admin/appointments', ['as' => 'admin.appointments', 'uses' => 'AppointmentController@index']);
Route::get('admin/settings', ['as' => 'admin.settings', 'uses' => 'SettingController@index']);

// Admin User Routes
Route::get('admin/users', ['as' => 'admin.users', 'uses' => 'UserController@index']);
Route::get('admin/users/edit/{id}', ['as' => 'admin.users.edit', 'uses' => 'UserController@edit']);
Route::get('admin/user/create', ['as' => 'admin.users.create', 'uses' => 'UserController@create']);
Route::post('admin/user/create', ['as' => 'user.store', 'uses' => 'UserController@store']);
Route::put('user/{id}', ['as' => 'user.update', 'uses' => 'UserController@update']);

// Admin Supplier Routes
Route::get('admin/suppliers', ['as' => 'admin.suppliers', 'uses' => 'AdminController@getSuppliers']);
Route::get('admin/suppliers/edit/{id}', ['as' => 'admin.suppliers.edit', 'uses' => 'AdminController@getSupplierEdit']);
Route::get('admin/suppliers/show/{id}', ['as' => 'admin.suppliers.show', 'uses' => 'AdminController@getSupplierShow']);

// Admin Customer Routes
Route::get('admin/customers', ['as' => 'admin.customers', 'uses' => 'AdminController@getCustomers']);
Route::get('admin/customers/edit/{id}', ['as' => 'admin.customers.edit', 'uses' => 'AdminController@getCustomerEdit']);
Route::get('admin/customers/show/{id}', ['as' => 'admin.customers.show', 'uses' => 'AdminController@getCustomerShow']);

// Admin Appointments Routes
Route::get('admin/appointment/edit/{id}', ['as' => 'admin.appointment.edit', 'uses' => 'AppointmentController@edit']);

// Customer Routes
Route::get('customer', ['as' => 'customer.index', 'uses' => 'CustomerController@index']);
Route::get('customer/bookings', ['as' => 'customer.bookings', 'uses' => 'CustomerController@getBookings']);
Route::put('customer/{id}', ['uses' => 'CustomerController@update', 'as' => 'customer.update']);

// Booking Routes & Paypal Routes
Route::resource('booking', 'AppointmentController', ['except' => ['destroy', 'create', 'index', 'store']]);

Route::get('booking', ['as' => 'booking.create', 'uses' => 'AppointmentController@create']);
//Route::post('booking/create', ['as' => 'booking.create', 'uses' => 'AppointmentController@create']);

Route::get('booking-status', ['as' => 'booking.status','uses' => 'PayPalController@getPayWithPaypal']);

Route::post('booking', ['as' => 'addmoney.paypal','uses' => 'PayPalController@postPayWithPaypal']);
Route::get('paypal', ['as' => 'payment.status','uses' => 'PayPalController@getPaymentStatus']);

// Tag Routes
Route::resource('tag', 'TagController', ['except' => ['show', 'create', 'index']]);

// Treatment Routes
Route::resource('treatment', 'TreatmentController', ['except' => ['create', 'show', 'index']]);

// Service Routes
Route::resource('service', 'ServiceController', ['except' => ['create', 'index']]);

// Supplier Routes
Route::get('supplier', ['as' => 'supplier', 'uses' => 'SupplierController@index']);
Route::get('supplier/register', ['as' => 'supplier.register', 'uses' => 'PagesController@getSupplierRegistration']);
Route::get('supplier/availability', ['as' => 'supplier.availability', 'uses' => 'SupplierController@getAvailability']);
Route::get('supplier/holidays', ['as' => 'supplier.holiday', 'uses' => 'SupplierController@getHoliday']);

Route::get('supplier/services', ['as' => 'supplier.services', 'uses' => 'SupplierController@getServices']);
Route::get('supplier/create', ['as' => 'supplier.create', 'uses' => 'SupplierController@getCreateListing']);
Route::get('supplier/edit/{id}', ['as' => 'supplier.edit', 'uses' => 'SupplierController@getServiceEdit']);

Route::post('supplier/register', ['as' => 'supplier.register', 'uses' => 'Auth\RegisterController@register']);
Route::post('supplier/{user_id}', ['uses' => 'SupplierController@store', 'as' => 'supplier.store']);
Route::put('supplier/{id}', ['uses' => 'SupplierController@update', 'as' => 'supplier.update']);

Route::get('supplier/appointments', ['as' => 'supplier.appointments', 'uses' => 'SupplierController@getAppointments']);

Route::get('supplier/appointment/{id}', ['as' => 'supplier.appointment.show', 'uses' => 'SupplierController@getShowAppointment']);
Route::get('supplier/appointment/edit/{id}', ['as' => 'supplier.appointment.edit', 'uses' => 'SupplierController@getEditAppointment']);

// Holiday Routes
Route::resource('holiday', 'HolidayController', ['except' => ['index', 'update', 'edit', 'create', 'show']]);

// Setting Routes
Route::resource('setting', 'SettingController', ['except' => ['create', 'show', 'index', 'edit', 'store', 'destroy']]);

resources/views/admin/appointments.blade.php
@extends('layouts.admin')

@section('title', 'Admin Appointments')

@section('stylesheets')

@endsection

@section('content')

    <div id="admin_header">
        @include('partials.admin._toggle')

        <h2>
            <i class="fa fa-calendar mr-10"></i> Appointments
        </h2>

        <span class="pull-right">
            <a href="{{ route('/') }}" class="btn btn-md btn-blank"><i class="fa fa-home"></i> Visit Site</a>
        </span>
    </div>

    <div id="action_panel" class="bg-beige">
        <h5>There {{ $appointments->count() === 1 ? 'is' : 'are' }} <span
                    class="badge">{{ $appointments->count() }}</span>
            appointment{{ $appointments->count() === 1 ? '' : 's' }}.</h5>
        <div class="clearfix"></div>
    </div>

    <section>
        <div class="container-fluid">
            @if($appointments->count() === 0)

                <div class="row">
                    <div class="col-sm-12">
                        <p>There are no appointments listed.</p>
                    </div>
                </div>

            @else

                <div class="row">
                    <div class="col-sm-12">
                        <div class="panel panel-body panel-default bg-white npadding">
                            <div class="table-responsive">
                                <table id="customers-index" class="table table-bordered">
                                    <thead class="">
                                    <th>
                                        Order No.
                                    </th>
                                    <th>Custom No.</th>
                                    <th>Supplier No.</th>
                                    <th>Duration</th>
                                    <th>Total Price</th>
                                    <th>Date</th>
                                    <th>Time of Day</th>
                                    <th>Paid</th>
                                    <th>Confirmed</th>
                                    <th>Canceled</th>
                                    </thead>

                                    <tbody>
                                    @foreach($appointmentsPaginate as $appointment)

                                        <tr id="appointment-{{ $appointment->id }}">
                                            <td>
                                                <a href="{{ route('admin.appointment.edit', $appointment->id) }}">
                                                    <strong>
                                                        #ORD-0{{ $appointment->id }}
                                                    </strong>
                                                </a>
                                            </td>
                                            <td>
                                                <strong>
                                                    #00{{ $appointment->customer->id }}

                                                </strong>
                                            </td>
                                            <td>
                                                <strong>
                                                    #SUP-0{{ $appointment->supplier->id }}

                                                </strong>
                                            </td>
                                            <td>
                                                {{ $appointment->duration > 1 ? "$appointment->duration hrs" : "$appointment->duration hr" }}
                                            </td>
                                            <td>
                                                &pound;{{ $appointment->price }}
                                            </td>
                                            <td>
                                                {{ date('d/m/Y' , strtotime($appointment->date)) }}
                                            </td>
                                            <td>
                                                {{ $appointment->time_of_day }}
                                            </td>
                                            <td class="text-center">
                                                @if($appointment->payment_received === 0)
                                                    <span class="label label-xs label-danger">No</span>
                                                @else
                                                    <span class="label label-xs label-success">Yes</span>
                                                @endif
                                            </td>
                                            <td class="text-center">
                                                @if($appointment->supplier_confirmed === 0)
                                                    <span class="label label-xs label-danger">No</span>
                                                @else
                                                    <span class="label label-xs label-success">Yes</span>
                                                @endif
                                            </td>

                                            <td class="text-center">
                                                @if($appointment->canceled === 0)
                                                    <span class="label label-xs label-danger">No</span>
                                                @else
                                                    <span class="label label-xs label-success">Yes</span>
                                                @endif
                                            </td>
                                        </tr>

                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>

                    </div>

                    <div class="clearfix"></div>

                    <div class="pl-15 pull-left pt-5">
                        Page <strong>{!! $appointmentsPaginate->currentPage() !!}</strong>
                        of {!! $appointmentsPaginate->lastPage() !!}
                    </div>

                    <div class="pull-right pr-15">
                        {!! $appointmentsPaginate->links() !!}
                    </div>
                </div>

            @endif

            <div class="row mt-20">
                <div class="col-sm-12">
                    <a href="{{ route('admin') }}" class="btn btn-md btn-beige">back</a>
                </div>
            </div>
        </div>
    </section>

@stop

@section('scripts')

@stop

resources/views/admin/index.blade.php
{{--Dashboard Page--}}

@extends('layouts.admin')

@section('title', 'Admin')

@section('stylesheets')

@endsection

@section('content')

    <div id="admin_header">
        @include('partials.admin._toggle')

        <h2>
            <i class="fa fa-th mr-10"></i> Dashboard
        </h2>

        <span class="pull-right">
            <a href="{{ route('/') }}" class="btn btn-md btn-blank"><i class="fa fa-home"></i> Visit Site</a>
        </span>
    </div>

    <section>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12 col-md-6">
                    <div class="panel panel-default bg-light-blue">
                        <div class="panel-body">
                            <h3 class="nmargin">Recent Suppliers
                                @if($activeSuppliers->count() > 0)
                                    <span class="badge">{{ $activeSuppliers->count() }}</span>
                                @endif
                            </h3>

                            <hr class="mt-10 mb-10">

                            @if($suppliers->count() === 0)
                                <p class="nmbottom">
                                    You do not have any suppliers registered
                                </p>
                            @else
                                <div class="clearfix"></div>
                                <ul class="pl-20 mt-5 nmbottom">
                                    @foreach($suppliersPaginate as $supplier)

                                        <li class="medium mb-5">
                                            <a class="text-white" href="{{ route('admin.suppliers.show', $supplier->id) }}">
                                                <span class="visible-lg-inline visible-md-inline">{{ $supplier->company }}</span>
                                                <span class="visible-sm-inline visible-xs-inline">{{ substr(strip_tags($supplier->company), 0, 15) }}{{ strlen(strip_tags($supplier->company)) > 15 ? "..." : "" }}</span>
                                            </a>


                                            @if($supplier->active === 0)
                                                <span class="pull-right label label-danger" style="font-size: 90%;">Not Active</span>
                                            @else
                                                <span class="pull-right label label-success" style="font-size: 90%;">Active</span>
                                            @endif

                                        </li>

                                    @endforeach
                                </ul>
                            @endif
                        </div>

                        <div class="panel-footer pt-15 pb-15 bg-dark-blue nborder nb-radius">
                            <h6 class="nmbottom xs-text-center">
                                You have <a href="{{ route('admin.suppliers') }}" class=""><span class="badge">{{ $inActiveSuppliers->count() }}</span></a> in-activated suppliers.

                                <span class="pull-right">
                                    <a href="{{ route('admin.suppliers') }}" class="text-white">(View all suppliers)</a>
                                </span>

                                <div class="clearfix"></div>
                            </h6>
                        </div>

                    </div>
                </div>

                <div class="col-sm-12 col-md-6">
                    <div class="panel panel-default bg-teal">
                        <div class="panel-body">
                            <h3 class="">Recent Customers
                                @if($customers->count() > 0)
                                    <span class="badge">{{ $customers->count() }}</span>
                                @endif
                            </h3>

                            <hr class="mt-10 mb-10">

                            @if($customers->count() === 0)
                                <p class="nmbottom">
                                    You do not have any customers registered
                                </p>
                            @else
                                <div class="clearfix"></div>
                                <ul class="pl-20 mt-5 nmbottom">
                                    @foreach($customersPaginate as $customer)

                                        <li class="medium mb-5">
                                            <a class="text-white" href="{{ route('admin.customers.show', $customer->id) }}">
                                                <span class="visible-lg-inline visible-md-inline">
                                                    {{ $customer->user->firstname . ' ' . $customer->user->lastname }}
                                                </span>
                                                <span class="visible-sm-inline visible-xs-inline">
                                                    {{ substr(strip_tags($customer->user->firstname . ' ' . $customer->user->lastname), 0, 15) }}{{ strlen(strip_tags($customer->user->firstname . ' ' . $customer->user->lastname)) > 15 ? "..." : "" }}
                                                </span>
                                            </a>

                                            @if($customer->active === 0)
                                                <span class="pull-right label label-danger" style="font-size: 90%;">Not Active</span>
                                            @else
                                                <span class="pull-right label label-success" style="font-size: 90%;">Active</span>
                                            @endif
                                        </li>

                                    @endforeach
                                </ul>
                            @endif
                        </div>

                        <div class="panel-footer pt-15 pb-15 bg-dark-teal nborder nb-radius">
                            <h6 class="nmbottom text-right xs-text-center">
                                <a href="{{ route('admin.suppliers') }}" class="text-white">(View all customers)</a>
                            </h6>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row mt-10">
                <div class="col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-heading pt-20 pb-20">
                            <h3 class="text-dark-gray nmbottom">Recently Added Services</h3>
                        </div>
                        <div class="panel-body text-dark-gray npadding" style="background-color: #fcfcfc;">

                            @if($services->count() === 0)
                                <p class="nmbottom pl-15 mt-10 mb-10">
                                    There are no listed services.
                                </p>
                            @else
                                <div class="clearfix"></div>
                                <div class="table-responsive">
                                    <table id="services-index" class="table pl-10 nmbottom">
                                        <thead class="bg-light-gray nb-radius">
                                            <th class="nbleft" style="width:200px;">Title</th>
                                            <th style="width:250px;">Company</th>
                                            <th style="width:100px;">Service</th>
                                            <th>Price p/h</th>
                                            <th>Sale</th>
                                            <th>Sale Price</th>
                                            <th class="nbright" style="width:80px;">Status</th>
                                        </thead>

                                        <tbody class="">
                                        @foreach($servicesPaginate as $service)

                                            <tr id="service-{{ $service->id }}">
                                                <td class="nbleft">
                                                    <a href="{{ route('service.show', $service->id) }}"><span class="">{{ $service->title }}</span></a>
                                                </td>
                                                <td>
                                                    {{ $service->supplier->company }}
                                                </td>
                                                <td>
                                                    <span class="hidden">{!! $treat = $treatments->where('id', $service->service_type)->first() !!}</span>
                                                    {{ $treat->name }}
                                                </td>
                                                <td class="slug">
                                                    <strong>&pound;{{ $service->price }}</strong>
                                                </td>
                                                <td class="promotion-label">
                                                    @if( $service->promotion === 0 )
                                                        <label class="label label-danger {{-- nbradius --}}">Off</label>
                                                    @else
                                                        <label class="label label-success {{-- nbradius --}}">on</label>
                                                    @endif
                                                </td>
                                                <td class="promotion_price">
                                                    {{ $service->promotion_price !== null ? "&pound;$service->promotion_price" : 'N/A' }}
                                                </td>
                                                <td class="status-label nbright">
                                                    @if( $service->status == 'draft' )
                                                        <label class="label label-danger {{-- nbradius --}}">{{ $service->status }}</label>
                                                    @else
                                                        <label class="label label-success {{-- nbradius --}}">{{ $service->status }}</label>
                                                    @endif
                                                </td>
                                            </tr>

                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>

                            @endif

                        </div>
                        <div class="panel-footer pt-15 pb-15 bg-light-gray nborder nb-radius">
                            <h6 class="nmbottom text-right xs-text-center">
                                <a href="{{ route('admin.services') }}" class="text-dark-gray">(View all services)</a>
                            </h6>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


@stop

@section('scripts')

@stop

resources/views/admin/users.blade.php
@extends('layouts.admin')

@section('title', 'Admin | Users')

@section('stylesheets')

@endsection

@section('content')

    <div id="admin_header">
        @include('partials.admin._toggle')

        <h2>
            <i class="fa fa-users mr-10"></i> Users
        </h2>

        <span class="pull-right">
            <a href="{{ route('/') }}" class="btn btn-md btn-blank"><i class="fa fa-home"></i> Visit Site</a>
        </span>
    </div>

    <div id="action_panel" class="bg-beige">
        <h5>There {{ $users->count() === 1 ? 'is' : 'are' }} <span class="badge">{{ $users->count() }}</span> user{{ $users->count() === 1 ? '' : 's' }}.</h5>

        <a href="{{ route('admin.users.create') }}" class="btn btn-sm btn-dark-gray">add new user</a>

        <div class="clearfix"></div>
    </div>

    <section>
        <div class="container-fluid">
            @if($users->count() === 0)
                <div class="row">
                    <div class="col-sm-12">
                        <p>You don't have any registered customers</p>
                    </div>
                </div>

            @else
                <div class="row">
                    <div class="col-sm-12">
                        <div class="panel panel-body panel-default bg-white npadding">
                            <div class="table-responsive">
                                <table id="users-index" class="table table-bordered">
                                    <thead class="">
                                    <th style="width:220px;">Full Name</th>
                                    <th>Email</th>
                                    <th>Role</th>
                                    @if(Entrust::hasRole('super-admin'))
                                        <th style="width: 100px"></th>
                                    @endif
                                    </thead>

                                    <tbody>
                                        @foreach($usersPaginate as $user)

                                        <tr id="customer-{{ $user->id }}">
                                            <td>
                                                <a href="{{ route('admin.users.edit', $user->id) }}">{{ $user->firstname . ' ' . $user->lastname }}</a>
                                            </td>
                                            <td>
                                                {{ $user->email }}
                                            </td>
                                            <td>
                                                @if(!empty($user->roles))
                                                    @foreach($user->roles as $role)
                                                        <label for="label label-success">{{ $role->display_name }}</label>
                                                    @endforeach
                                                @endif
                                            </td>
                                            @if(Entrust::hasRole('super-admin'))
                                            <td class="text-center">
                                                <a href="{{ route('admin.users.edit', $user->id) }}" class="medium text-dark-gray">[edit]</a>
                                            </td>
                                            @endif

                                        </tr>

                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>

                    </div>

                    <div class="clearfix"></div>

                    <div class="pl-15 pull-left pt-5">
                        Page <strong>{!! $usersPaginate->currentPage() !!}</strong> of {!! $usersPaginate->lastPage() !!}
                    </div>

                    <div class="pull-right pr-15">
                        {!! $usersPaginate->links() !!}
                    </div>
                </div>
            @endif

                <div class="row mt-30">
                    <div class="col-sm-12">
                        <a href="{{ route('admin') }}" class="btn btn-md btn-beige">back</a>
                    </div>
                </div>
        </div>
    </section>


@stop

@section('scripts')

@stop